### User
POST http://localhost:1337/api/users
Content-Type: application/json

{
    "data": {
        "name" : "test",
        "mdp": "test"
    }

}

### User
GET http://localhost:1337/api/users

### Classe
POST http://localhost:1337/api/classes
Content-Type: application/json

{
    "data": {
        "name" : "B3"
    }

}

### Classe
GET http://localhost:1337/api/classes

### Eleve
POST http://localhost:1337/api/eleves
Content-Type: application/json

{
    "data": {
        "name" : "Tata",
        "classeId": 1
    }

}

### Eleve
GET http://localhost:1337/api/eleves


### Groupe
POST http://localhost:1337/api/groupes
Content-Type: application/json

{
    "data": {
        "name" : "Tutu"
    }

}

### Groupe
GET http://localhost:1337/api/groupes